### ISSUE TITLE
Dead dataset link

### ISSUE THREAD

**Issue by felixlaumon** [stencilman/deep_nets_iclr04#1]
The link http://vajra.cs.nyu.edu/iclr04/full-images.zip provided in `deep_nets_iclr04/data/FLIC/process.py` is no longer reachable.

Some of the `*.mat` files (e.g. [here](https://github.com/stencilman/deep_nets_iclr04/blob/master/lib/data_processing.py#L47-L49)) are not available in the publicly accessible download link http://vision.grasp.upenn.edu/cgi-bin/index.php?n=VideoLearning.FLIC

Is the dataset available at another link? Thanks!

**Comment by stencilman** [comment]
Hi @felixlaumon, thanks for the issue. Yes, you are right, the file is gone from the server and I dont have a copy. We have two options:
1. I can try to recreate the zip, I will try to dig up the .mat files
2. I know some other ppl who downloaded this, I can try to get the .zip file from them.

@ruoyanwang, can you please help us and give us a copy of full-images.zip that you may have locally?

**Comment by SeninAndrew** [comment]
Hi @stencilman ! I would love to try running this code. But faced the same problem with missing zip file. Did you manage to find someone who has the copy of the zip or mat files? Thanks!

**Comment by ruoyanwang** [comment]
@SeninAndrew 
I received several mails asking for the zip files so I uploaded them to my google drive.
full-images.zip: https://drive.google.com/open?id=0B0RmDFCOYngXZW1PcW5WdVlFUUE&authuser=0
mat.zip: https://drive.google.com/open?id=0B0RmDFCOYngXSkxOazlXV2lLM28&authuser=0
Those files are probably not in their original format, so plz double-check them to make sure it works.

Best,
Ryan

**Comment by SeninAndrew** [comment]
@ruoyanwang , thanks a lot! The files worked for me!

**Comment by ruoyanwang** [comment]
@SeninAndrew Glad I can help!

**Comment by stencilman** [comment]
Thanks a lot @ruoyanwang you have been a life saver for so many people! :-)

Dear @SeninAndrew , If you find time, if you can submit a PR which will fix this, I will be very happy to merge it as it will help others after you.

**Comment by SeninAndrew** [comment]
@stencilman , just created a PR. Please let me know if it looks good to you. Thanks!
