### ISSUE TITLE
Expected train time

### ISSUE THREAD

**Issue by SeninAndrew** [stencilman/deep_nets_iclr04#3]
Hi @stencilman ! Could you please share some statistics on expected training time on off-the-shelf hardware?

I'm trying to train the model on my i5 3.3 GHz, 16GB, Nvidia GTX 750 Ti, 2GB. It is already running for 4 or 5 days. It has completed 1900 epochs. Each epoch takes 0.27 mins to compute. And most of time is taken for weak negatives mining which is executed each 50 epochs (I'm using the default parameters, only batch size is decreased to 64 to fit GPU memory). How much time do you think is left? Thanks!

**Comment by stencilman** [comment]
I did my negative mining on a cpu cluster and thus I could do many rounds of negative mining. I think the model you have currently will do something, but not as well as reported in the ICLR paper. Moreover, we have moved away from the sliding window model to one shot model, and you can easily convert this code to do what we do in our NIPS/ACCV papers.
